files:
- generatedChecksum: AB67D8A7D0606ADFF3E9184E6CB5B5F9
  logicalPath: config/pic32mz2048efg144
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: AB67D8A7D0606ADFF3E9184E6CB5B5F9
- generatedChecksum: 5E39C2E47758B1982D6D21E09C78B2FB
  logicalPath: config/pic32mz2048efg144
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 5E39C2E47758B1982D6D21E09C78B2FB
- generatedChecksum: D10EB71AC34B377C94B89524E30E99A2
  logicalPath: config/pic32mz2048efg144
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: D10EB71AC34B377C94B89524E30E99A2
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: E4FCCCE73569E122C9AB898C49D3C1EB
  logicalPath: config/pic32mz2048efg144/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: E4FCCCE73569E122C9AB898C49D3C1EB
- generatedChecksum: 69EAE9C44598FBEE36D428B9C253F583
  logicalPath: config/pic32mz2048efg144/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 69EAE9C44598FBEE36D428B9C253F583
- generatedChecksum: 612AD727CDBFAC6FD0B4B722DC388BF9
  logicalPath: config/pic32mz2048efg144/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 612AD727CDBFAC6FD0B4B722DC388BF9
- generatedChecksum: 451DBD4978CF3ECC195A212174414B4F
  logicalPath: config/pic32mz2048efg144/peripheral/nvm
  name: plib_nvm.c
  physicalPath: peripheral/nvm
  security: NON_SECURE
  type: SOURCE
  userChecksum: 451DBD4978CF3ECC195A212174414B4F
- generatedChecksum: BCDC387E1774D6F72579EBB950B8AAF7
  logicalPath: config/pic32mz2048efg144/peripheral/spi/spi_master
  name: plib_spi1_master.c
  physicalPath: peripheral/spi/spi_master
  security: NON_SECURE
  type: SOURCE
  userChecksum: BCDC387E1774D6F72579EBB950B8AAF7
- generatedChecksum: AA8ED0C7C62E5F640F435BA9C6B00C49
  logicalPath: config/pic32mz2048efg144/peripheral/tmr1
  name: plib_tmr1.c
  physicalPath: peripheral/tmr1
  security: NON_SECURE
  type: SOURCE
  userChecksum: AA8ED0C7C62E5F640F435BA9C6B00C49
- generatedChecksum: A73781AA73D01E786524F13C46BD795E
  logicalPath: config/pic32mz2048efg144/peripheral/uart
  name: plib_uart5.c
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: A73781AA73D01E786524F13C46BD795E
- generatedChecksum: D2B5BDC2F4578FDBBADED01931AF6259
  logicalPath: config/pic32mz2048efg144/peripheral/wdt
  name: plib_wdt.c
  physicalPath: peripheral/wdt
  security: NON_SECURE
  type: SOURCE
  userChecksum: D2B5BDC2F4578FDBBADED01931AF6259
- generatedChecksum: C95CE0ABB86E6B11CF77E8891D294510
  logicalPath: config/pic32mz2048efg144/system/int
  name: sys_int.c
  physicalPath: system/int/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: C95CE0ABB86E6B11CF77E8891D294510
- generatedChecksum: 47B584985982B2FF32628D4CB874CB4D
  logicalPath: config/pic32mz2048efg144/system/reset
  name: sys_reset.c
  physicalPath: system/reset
  security: NON_SECURE
  type: SOURCE
  userChecksum: 47B584985982B2FF32628D4CB874CB4D
- generatedChecksum: 7806B30ECAE0D18D08CD583D8775530D
  logicalPath: config/pic32mz2048efg144/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7806B30ECAE0D18D08CD583D8775530D
- generatedChecksum: 67A5AC50A1301E3B067402B763972CBD
  logicalPath: config/pic32mz2048efg144
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 67A5AC50A1301E3B067402B763972CBD
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mz2048efg144
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mz2048efg144
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mz2048efg144/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 8B79859DBC780EA12969B9D3099178DE
  logicalPath: config/pic32mz2048efg144/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 8B79859DBC780EA12969B9D3099178DE
- generatedChecksum: 2886151876856172CBE26C4AEDB695CE
  logicalPath: config/pic32mz2048efg144/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 2886151876856172CBE26C4AEDB695CE
- generatedChecksum: 7C954B20EDAB3F13455008470691E59C
  logicalPath: config/pic32mz2048efg144/peripheral/nvm
  name: plib_nvm.h
  physicalPath: peripheral/nvm
  security: NON_SECURE
  type: HEADER
  userChecksum: 7C954B20EDAB3F13455008470691E59C
- generatedChecksum: A9C21E81CB403E638EEB811A7780088B
  logicalPath: config/pic32mz2048efg144/peripheral/spi/spi_master
  name: plib_spi1_master.h
  physicalPath: peripheral/spi/spi_master
  security: NON_SECURE
  type: HEADER
  userChecksum: A9C21E81CB403E638EEB811A7780088B
- generatedChecksum: CFA758C8B7258190473EF7C60C4BA4E9
  logicalPath: config/pic32mz2048efg144/peripheral/spi/spi_master
  name: plib_spi_master_common.h
  physicalPath: peripheral/spi/spi_master
  security: NON_SECURE
  type: HEADER
  userChecksum: CFA758C8B7258190473EF7C60C4BA4E9
- generatedChecksum: 32D7539D9231F3C159ABECE91A0281EA
  logicalPath: config/pic32mz2048efg144/peripheral/tmr1
  name: plib_tmr1.h
  physicalPath: peripheral/tmr1
  security: NON_SECURE
  type: HEADER
  userChecksum: 32D7539D9231F3C159ABECE91A0281EA
- generatedChecksum: 69E7C8CDAB1B32838331EE261170CEA4
  logicalPath: config/pic32mz2048efg144/peripheral/tmr1
  name: plib_tmr1_common.h
  physicalPath: peripheral/tmr1
  security: NON_SECURE
  type: HEADER
  userChecksum: 69E7C8CDAB1B32838331EE261170CEA4
- generatedChecksum: 0E7D6E9DD000E6E483B566F19809A0B0
  logicalPath: config/pic32mz2048efg144/peripheral/uart
  name: plib_uart5.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 0E7D6E9DD000E6E483B566F19809A0B0
- generatedChecksum: 91611515A95D92B82B7F4064C16D122B
  logicalPath: config/pic32mz2048efg144/peripheral/uart
  name: plib_uart_common.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 91611515A95D92B82B7F4064C16D122B
- generatedChecksum: 52646F9F1734C5AA98A212549F6FE3E3
  logicalPath: config/pic32mz2048efg144/peripheral/wdt
  name: plib_wdt.h
  physicalPath: peripheral/wdt
  security: NON_SECURE
  type: HEADER
  userChecksum: 52646F9F1734C5AA98A212549F6FE3E3
- generatedChecksum: 47330C2D8F204B2B69F8A86240A564B6
  logicalPath: config/pic32mz2048efg144/system/int
  name: sys_int.h
  physicalPath: system/int
  security: NON_SECURE
  type: HEADER
  userChecksum: 47330C2D8F204B2B69F8A86240A564B6
- generatedChecksum: FC7B55936A09E0CA1395AE4DFB1A188F
  logicalPath: config/pic32mz2048efg144/system/int
  name: sys_int_mapping.h
  physicalPath: system/int
  security: NON_SECURE
  type: HEADER
  userChecksum: FC7B55936A09E0CA1395AE4DFB1A188F
- generatedChecksum: 8E43BD17134E69982826F202D0AB42C5
  logicalPath: config/pic32mz2048efg144/system/reset
  name: sys_reset.h
  physicalPath: system/reset
  security: NON_SECURE
  type: HEADER
  userChecksum: 8E43BD17134E69982826F202D0AB42C5
- generatedChecksum: CAC44960D20AEC03CF4B325A1CD2877C
  logicalPath: config/pic32mz2048efg144
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: CAC44960D20AEC03CF4B325A1CD2877C
- generatedChecksum: B0ABE2DA63F82A99247A6C8A42E4C59D
  logicalPath: config/pic32mz2048efg144
  name: p32MZ2048EFG144.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: B0ABE2DA63F82A99247A6C8A42E4C59D
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz2048efg144;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz2048efg144;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
