format_version: v1.0
type: UniqueComponent
attributes: {id: tmr1}
children:
- type: Symbols
  children:
  - type: Hex
    attributes: {id: TCON_REG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr1, value: '16'}
  - type: Integer
    attributes: {id: TIMER1_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr1, value: '12500000'}
  - type: Long
    attributes: {id: TIMER1_PERIOD}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr1, value: '6249'}
  - type: KeyValueSet
    attributes: {id: TIMER1_PRE_SCALER}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '2'}
  - type: Float
    attributes: {id: TIMER1_TIME_PERIOD_MS}
    children:
    - type: Attributes
      children:
      - type: Float
        attributes: {id: max}
        children:
        - {type: Value, value: '5242.96'}
    - type: Values
      children:
      - type: User
        attributes: {value: '500.0'}
  - type: Combo
    attributes: {id: TIMER_UNIT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: microsecond}
  - type: Integer
    attributes: {id: TMR1_PRESCALER_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr1, value: '8'}
- type: ElementPosition
  attributes: {x: '22', y: '229', id: tmr1}
